language: node_js
node_js:
- '8'
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    branch: master
  email: luca.catallo.293@gmail.com
  api_key:
    secure: XktKrn1hS0Jqmeldx8W1QI8Qptk06GBml/sq/gjCFNj5/wLcpJFDtJoK2KAXyrrIKarTRibIXyYtmIC0mIRmz2de8qBa1XPnbWUu4QhqscyZ00D+iSkRM3Pojc4+u53arcXhkfjLw8XsqHwVvl0kYtDzYLASndpbSUDO6T2wuaewLz+b/tqQwxwj8cMEtp8u7QjR4RYjjnrnxYj95UH4vKeCcTSkuI5JN5Gn5xcXt7cJOG27l0z/R8IfW5n2Y1smfHO6+9w2drBPy6f94IngPIkSxkIhT6S4X+zesfxz7642pxDm5WD/fhYrFJuw/ZdjNlEO3yyXTEalPWqRnbM+FfDkr80rxTZDB5PNq+xrZiZOWB873h3HM3oQSL+3a++RDPsmnnUc3pXuThFVVe8ApHRokigpHITedfoZ7O+86tOYvHHMnX1l1wQDpOnmdPCTOZ5e44J4t5zXEhTGvaw4H0lk1vbK2+N5L09JuEwKAS/V9kvyQeiLoZd65MeqHXho0s3Ou8/BqLkZ44gIhOM3pK0sV9fy/bz6le86OJarQbtnOwzoA7OxdAtxEk0M0o8aWxHubILcXoNtVXh8nTEcB193YlBv8kH4MlRcPicsIa2MHDsGIHO4zfQDfBixKQGE3eKQBhev6rmiY3LXsl7z+1FB04O2oel1e58FHsrAPTk=
